builders:
  interface_builder:
    import: "package:interface_generator/builder.dart"
    builder_factories: ["interfaceBuilder"]
    build_extensions: {".dart": [".interface.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
